spring:
  main:
    web-application-type: reactive
  application:
    name: hash-translator
grpc:
  client:
    authorizationService:
      address: 'static://localhost:9090'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
logging:
  level:
    org.springframework.web: DEBUG